# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x0ciotlakehouse\"\x93\x01\n\tTelemetry\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07site_id\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\x03\x12\x15\n\rtemperature_c\x18\x04 \x01(\x01\x12\x14\n\x0chumidity_pct\x18\x05 \x01(\x01\x12\x14\n\x0cpressure_hpa\x18\x06 \x01(\x01\x12\x13\n\x0bvibration_g\x18\x07 \x01(\x01\x42\x38\n&com.github.ghoshp83.iotlakehouse.protoB\x0eTelemetryProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&com.github.ghoshp83.iotlakehouse.protoB\016TelemetryProto'
  _globals['_TELEMETRY']._serialized_start=34
  _globals['_TELEMETRY']._serialized_end=181
# @@protoc_insertion_point(module_scope)
