#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "[gen_proto] Generating Python stubs from proto/telemetry.proto"
python3 -m grpc_tools.protoc \
    -I="$REPO_ROOT/proto" \
    --python_out="$REPO_ROOT/sample-data" \
    "$REPO_ROOT/proto/telemetry.proto"

echo "[gen_proto] Generated sample-data/telemetry_pb2.py"
echo "[gen_proto] Java stubs are generated by Maven: cd flink-jobs && mvn compile"
